"use client";

import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./context/themeContext";
import { ResponsiveProvider } from "./context/ResponsiveContext";
import { Provider } from "react-redux";
import { store } from "./lib/store";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
// 	title: "Create Next App",
// 	description: "Generated by create next app",
// };

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<>
			<html lang="en">
				<head>
					<title>Invoice App</title>
					<link rel="icon" href={"/assets/logo.svg"} type="image/png" />
					<meta name="description" content="Generated by create next app" />
				</head>

				<body className={`${inter.className}`}>
					<Provider store={store}>
						<ResponsiveProvider>
							<ThemeProvider>{children}</ThemeProvider>
						</ResponsiveProvider>
					</Provider>
				</body>
			</html>
		</>
	);
}
